name: li_webview_example
description: Demonstrates how to use the li_webview plugin.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  li_webview:
    path: ../

flutter:

  uses-material-design: true